service:
  modules: {"salt": "salt.states.service", "ansible": "ansible.modules.service"}
  functions: {"started": "service.running", "stopped": "service.dead"}
pip:
  modules: {"salt": "salt.states.pip_state", "ansible": "ansible.modules.pip"}
  functions: {"absent": "pip.removed", "present": "pip.installed"}
group:
  modules: {"salt": "salt.states.group", "ansible": "ansible.modules.group"}
  functions: {"present": "group.present", "absent": "group.absent"}
user:
  modules: {"salt": "salt.states.user", "ansible": "ansible.modules.user"}
  functions: {"present": "user.present", "absent": "user.absent"}
iptables:
  modules: {"salt": "salt.states.iptables", "ansible": "ansible.modules.iptables"}
  functions: {"present": "iptables.append", "absent": "iptables.delete"}
pkg:
  modules: {"salt": "salt.states.pkg", "ansible": "ansible.modules.pkg"}
  functions: {"present": "pkg.installed", "latest": "pkg.latest", "absent": "pkg.removed"}
git:
  modules: {"salt": "salt.states.git", "ansible": "ansible.modules.git"}
  functions: {"false": "git.cloned"}
  manual_args: {"repo": "name", "dest": "target", "version": "branch"}
archive:
  modules: {"salt": "salt.states.archive", "ansible": "ansible.modules.unarchive"}
  functions: {"false": "archive.extracted"}
  manual_args: {"src": "source", "dest": "name", "extra_opts": "options", "validate_certs": "skip_verify"}
cmd:
  modules: {"salt": "salt.states.cmd", "ansible": "ansible.modules.command"}
  functions: {"false": "cmd.run"}
  manual_args: {"cmd": "name", "chdir": "cwd", "creates": "creates"}
script:
  modules: {"salt": "salt.states.cmd", "ansible": "ansible.modules.script"}
  functions: {"false": "cmd.script"}
  manual_args: {"creates": "creates", "chdir": "cwd", "cmd": "name"}
pkgrepo:
  modules: {"salt": "salt.states.pkgrepo", "ansible": "ansible.modules.apt_repository"}
  functions: {"present": "pkgrepo.managed", "absent": "pkgrepo.absent"}
  setup_names: ["ansible.builtin.apt_repository", "ansible.builtin.yum_repository", "yum_repository"]
  manual_args: {"repo": "name", "filename": "file", "mirrorlist": "mirrorlist", "description": "humanname", "enabled": "enabled", "gpgkey": "gpgkey", "description": "humanname", "baseurl": "baseurl"}
cron:
  modules: {"salt": "salt.states.cron", "ansible": "ansible.modules.cron"}
  functions: {"present": "cron.present", "absent": "cron.absent"}
  setup_names: ["ansible.builtin.cron"]
  manual_args: {"name": "comment", "day": "daymonth", "job": "name", "special_time": "special", "weekday": "dayweek"}
mysql_user:
  modules: {"salt": "salt.states.mysql_user", "ansible": "ansible_collections.community.mysql.plugins.modules.mysql_user"}
  functions: {"present": "mysql_user.present", "absent": "mysql_user.absent"}
  setup_names: ["ansible.community.mysql"]
  manual_args: {}
mysql_db:
  modules: {"salt": "salt.states.mysql_database", "ansible": "ansible_collections.community.mysql.plugins.modules.mysql_db"}
  functions: {"present": "mysql_db.present", "absent": "mysql_db.absent"}
  setup_names: ["ansible.community.mysql"]
  manual_args: {}
