name: Pre-Commit

on:
  workflow_call:
    inputs:
      changed-files:
        required: true
        type: string
        description: JSON string containing information about changed files

jobs:
  Pre-Commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    container:
      image: python:3.10.9-slim-buster

    steps:

      - uses: actions/checkout@v3

      - name: Install Pre-Commit
        run: |
          # TODO: Update pip version without error
          #          python -m pip install --upgrade pip
          python -m pip install pip==19.3.1
          pip install pre-commit
          pre-commit install --install-hooks

      - name: Check ALL Files On Branch
        if: github.event_name != 'pull_request'
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Check Changed Files On PR
        if: github.event_name == 'pull_request' && fromJSON(inputs.changed-files)['repo'] == 'true'
        run: |
          pre-commit run --show-diff-on-failure --color=always --files ${{ join(fromJSON(inputs.changed-files)['repo_files'], ' ') }}

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error
